language: node_js
node_js:
- '0.12'
matrix:
  allow_failures: 
before_install:
- npm install -g npm@1.4.23
- cd sdk/node
- npm run-script setup
- npm install
- npm install -g grunt-cli
- npm install grunt --save-dev
- echo -n $id_rsa_{00..30} >> ~/.ssh/id_rsa_base64
- base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
- grunt genDocs
- grunt deploy
env:
  global:
    secure: pnBTydXUkA2EEeSOpplbJg/mH63DtgJpWDmMRxeGikmfwdG7N1kt6FzTo4Btc/MJ6vq2EYBtGMP1zCtm5GP4N5LaY8KAqHdogWu6exAvSC0K5d96M7OF9ubP3cQYZH6Mz8Yua/fSWvOuCnbErYFA6nYEBRSzLmBh+eMNakDw7aHQxELWnienD5EE1HcmieP8xSKH/v/U+8Vq4gI9ObHFfnq7/qXmrjO+B4TSJQ3njWZaw8QDZ2x/vK9UFwiHJmVTs6s39XV5aDTD/Nbds+Z3XMA998nb19rOj14wcihSwK8W0erIw07l1iClosfFf5qxFGbqH/J6k5cZIUXo8BEKZeNwyCbhi/lftZfMx6zuJRGhhOY0jhb1CeYGZW8SLCmd3FPFfIalqnsA2KsxySWsys/QV2mcvv221lfNbHiF+fw4FyfnD2KIXZsUoCve0bmD7dE7znoBYbILa9/d943WKYH3eEXxvYL0qRSJDST17Em+aomUH70m6rQGC51UzsExg5OKMQ7rJpImwnYeUcfhUJgNg/9QzCiL3FpN6Raz1a092c2YHPH+4oQeu2s/ro7LnTL88RBPlRf9PwJYx2kvOMNBvtrTo87xTiNiPNp2ybGgln7Veq6n+6/GLUVXpBtlRuT64zX8JqYlb4ydNnHoVyshNjT5UcHEO8wvCQE/Zvs=
