language: node_js
node_js:
- '0.12'
matrix:
  allow_failures: 
before_install:
- openssl aes-256-cbc -K $encrypted_661e73e75d1b_key -iv $encrypted_661e73e75d1b_iv
  -in deployKey.txt.enc -out deployKey.txt -d
- npm install -g npm@1.4.23
- cd sdk/node
- npm run-script setup
- npm install
- npm install -g grunt-cli
- npm install grunt --save-dev
script:
- grunt genDocs
- grunt deploy
