language: csharp
sudo: required
dist: trusty
env:
  global:
  - DNX_VERSION=1.0.0-rc1-final 
  - DNX_USER_HOME=~/.dnx
  #matrix:
  #- DNX_VERSION=1.0.0-rc1-final 
  #- DNX_USER_HOME=~/.dnx
mono:
- 4.0.5
os:
- linux
addons:
  apt:
    sources:
    - deadsnakes
    packages:
    # Packages for DNX    
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
install:
  - echo $DNX_VERSION
  # Install DNVM
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_USER_HOME=$DNX_USER_HOME
    DNX_BRANCH=v$DNX_VERSION sh
  - source $DNX_USER_HOME/dnvm/dnvm.sh
  - dnvm install $DNX_VERSION -r coreclr -alias default
  - dnvm alias default | xargs -i ln -s $DNX_USER_HOME/runtimes/{} $DNX_USER_HOME/runtimes/default
  # Install npm
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | sh && source ~/.dnx/dnvm/dnvm.sh && dnvm upgrade
  - npm install -g npm@'>=1.4.3'
  - npm install
  - cd sdk/node
  - npm run-script setup
  - npm install
  - npm install -g grunt-cli
  - npm install grunt --save-dev
  - cd ../dotnet
  - npm install
  - cd ../node
script:
  - dnvm install 1.0.0-rc1-final -r mono
  - dnvm install 1.0.0-rc1-final -r coreclr
  - dnvm use 1.0.0-rc1-final -r coreclr -persistent
  - pwd
  - ls -al
  # generate node sdk code
  - gulp codegen --spec-root ../../swagger
  # generate node sdk docs
  - grunt genDocs
  # publish node sdk docs
  - bash deploy.sh
  - cd ../dotnet 
  # generate dotnet sdk code
  - gulp codegen --spec-root ../../swagger
  # copy the static proj files
  - cp -avr src/Properties/ src/ResourceManagement/Resource/Microsoft.Azure.ResourceManager/Properties/
  - cp -avr src/Microsoft.Azure.ResourceManager.xproj src/ResourceManagement/Resource/Microsoft.Azure.ResourceManager/Microsoft.Azure.ResourceManager.xproj
  - cp -avr src/project.json src/ResourceManagement/Resource/Microsoft.Azure.ResourceManager/project.json
  - find . -name '*.cs'
  # generate dotnet sdk docs using Sandcastle (TBD) Move this to bash script
  - cd src/ResourceManagement/Resource/Microsoft.Azure.ResourceManager
  - ls -al
  - dnu --version
  - dnu restore
  - dnu list --details
  - dnu build
  - ls -al
  - cp -avr ../../../../tools/SandcastleARM.shfbproj bin/Debug/dnxcore50/SandcastleARM.shfbproj
  - cp -avr ../../../../tools/Sandcastle ~/Sandcastle/
  - cp -avr ../../../../tools/SandcastleHelpFileBuilder ~/SandcastleHelpFileBuilder
  - cd bin/Debug/dnxcore50
  - xbuild SandcastleARM.shfbproj
  - find . -name '*.*'
  - cd ../../..
  # publish dotnet sdk docs using bash script (TBD)
  # generate swagger ui docs TBD Move this to bash script
  - cd ../../../../
  - cd ../../swagger-ui/swagger
  - cp ../../swagger/arm-resource/resources/2014-04-01-preview/resources.json swagger.json
  - cd ..
  - bash publishSwaggerUI.sh
  #npm install -g http-server
  #bash startHttpSeverForCORS.sh
env:
  global:
    secure: ZlFb1c7WJvxQD7ErzjZ58UKbu27avP6ZWpiFbZ51K75Pw7vSe4RWthb91DmDPTgS/ALpcBxa1FfAz5aQZ9w9oAuJd4uSmbj2nTCpc+/HA+/l+ilsITmcAFhkuQ8fsQUDKK1DxrP6iYBukUTA2SD081xWCZ4c36OFZevc+4Z33aZ51PCZs+44BmLqjhTuJbauTZubsi6nbPglNJvOd1cJqeOcpTkjIpbwvyZAx8sZWc10YyrBBe+Eiun4t8w+6PS/djGjpCKvGI2Ll408Tm7DXcu8N0XEYz+nVJuEMIhuSD3UwKx/c6rqUvv1FACDQdiGwPRVSKvE5PFMcTZPVxWBcbe4mjAc0YdODG+OJZBa/ut6luWysrU8H39kh3bKwX6f1pNWoHxxW5hvqTEs1pVtF079CtuGDz17zBSyG3AQVyCjDe+pu+lA3bcNnCuLgR3auO1mL6V/TAUG9tqzTDzcrxT65NrOwmlb2aYdJrBFaYN75zQZkKti5jFthbmOugPJzynW59iEXOZLy3efl6J84Qed7k1btUzJptkQlPgjSL5/O5b5gl7RKyH4lM0xPARxBcfzUcb/huFywoOlyIl0Ka2swSiukZQFYtK1x8vs8VHIF+LHJYfaKt6RlbSaHpoAqmB+IL5Vo10MJzmZFHEXb8oo2tPx37RzUzsdp7vID70=