language: node_js
node_js: 
  - "0.12"

matrix:
  allow_failures:

# setup links to submodules
before_install:
  - npm install -g npm@1.4.23
  - cd sdk/node
  - npm run-script setup
  - npm install
  - npm install -g grunt-cli
  - npm install grunt --save-dev  
  #- cd ..
  #- git clone https://github.com/azure/azure-xplat-cli.git
  #- cd azure-xplat-cli
  #- git checkout dev
  #- node scripts/link-to-sdk.js
  #- npm install

script:
  - grunt genDocs
  - grunt deploy
  #- npm test
  #- cd ../azure-xplat-cli
  #- npm test
